package vibrointerpreter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.synthbot.jasiohost.AsioDriver;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JSlider;
/**
 *
 * @author imdc
 */
public class VibroGUI extends javax.swing.JFrame {
    
    private AsioDriver driver;
    protected AsioSoundHost listener;   
    protected boolean driverLoaded;
    
    boolean fileFound = false;
    JFileChooser c = new JFileChooser();
    int numChannels = 8;
    //MidiKeyboard kb = new MidiKeyboard();
      
    ArrayList <JProgressBar> bars = new ArrayList();
    ArrayList <JSlider> sliders = new ArrayList();
    ArrayList <JPanel> panels = new ArrayList();
    
    WaveFileReader waveFile;
    /**
     * Creates new form VibroGUI
     */
    public VibroGUI() {
        initComponents();
        setChannels(numChannels);
        /* load the driver */
        try {
            driver = AsioDriver.getDriver ( "ASIO PreSonus FireStudio" );
            listener = new AsioSoundHost ( driver );
            driver.start();
            driverLoaded = true;
        }
        catch ( UnsatisfiedLinkError e ){ 
            outText.setText("Please install the Following Driver: ASIO PreSonus FireStudio");
            System.out.println("Please install the Following Driver: ASIO PreSonus FireStudio");
            driverLoaded = false;
        }           
    }
    
    public void setChannels(int num){

        bars.clear();
        bars.add(visualBar1);
        bars.add(visualBar2);
        bars.add(visualBar3);
        bars.add(visualBar4);
        bars.add(visualBar5);
        bars.add(visualBar6);
        bars.add(visualBar7);
        bars.add(visualBar8);
        bars.add(visualBar9);
        bars.add(visualBar10);
        bars.add(visualBar11);
        bars.add(visualBar12);
        bars.add(visualBar13);
        bars.add(visualBar14);
        bars.add(visualBar15);
        bars.add(visualBar16);
        sliders.clear();
        sliders.add(volumeSlider1);
        sliders.add(volumeSlider2);
        sliders.add(volumeSlider3);
        sliders.add(volumeSlider4);
        sliders.add(volumeSlider5);
        sliders.add(volumeSlider6);
        sliders.add(volumeSlider7);
        sliders.add(volumeSlider8);
        sliders.add(volumeSlider9);
        sliders.add(volumeSlider10);
        sliders.add(volumeSlider11);
        sliders.add(volumeSlider12);
        sliders.add(volumeSlider13);
        sliders.add(volumeSlider14);
        sliders.add(volumeSlider15);
        sliders.add(volumeSlider16);
        panels.clear();       
        panels.add(jPanel4);
        panels.add(jPanel5);
        panels.add(jPanel6);
        panels.add(jPanel7);
        panels.add(jPanel8);
        panels.add(jPanel9);
        panels.add(jPanel10);
        panels.add(jPanel11);
        panels.add(jPanel12);
        panels.add(jPanel13);
        panels.add(jPanel14);
        panels.add(jPanel15);
        panels.add(jPanel16);
        panels.add(jPanel17);
        panels.add(jPanel18);
        panels.add(jPanel19);       
        for(int i=15; i>=0; i--){
            if(i>=num){
                sliders.remove(sliders.size()-1);
                bars.remove(bars.size()-1);
                panels.get(i).setVisible(false);               
            }else{
                panels.get(i).setVisible(true);
            }
        }
        numChannels=num;
        latencyPanel.setVisible(false);
        FreqFilter.write(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputGroup = new javax.swing.ButtonGroup();
        channelEnable = new javax.swing.ButtonGroup();
        freqSplitControl = new javax.swing.JDialog();
        ch1a = new javax.swing.JTextField();
        ch1b = new javax.swing.JTextField();
        ch2a = new javax.swing.JTextField();
        ch2b = new javax.swing.JTextField();
        ch3a = new javax.swing.JTextField();
        ch3b = new javax.swing.JTextField();
        ch4a = new javax.swing.JTextField();
        ch4b = new javax.swing.JTextField();
        ch5a = new javax.swing.JTextField();
        ch5b = new javax.swing.JTextField();
        ch6a = new javax.swing.JTextField();
        ch6b = new javax.swing.JTextField();
        ch7a = new javax.swing.JTextField();
        ch7b = new javax.swing.JTextField();
        ch8a = new javax.swing.JTextField();
        ch8b = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        freqSave = new javax.swing.JButton();
        freqControlTxt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        play = new javax.swing.JButton();
        outText = new javax.swing.JLabel();
        useMIDIFile = new javax.swing.JRadioButton();
        useMIDIDevice = new javax.swing.JRadioButton();
        outToDevice = new javax.swing.JRadioButton();
        useWaveFile = new javax.swing.JRadioButton();
        useWaveFile2 = new javax.swing.JRadioButton();
        latencyPanel = new javax.swing.JPanel();
        delayTuner = new javax.swing.JSlider();
        delayTunerLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        volumeSlider = new javax.swing.JSlider();
        visualBar_volume = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        volumeSlider1 = new javax.swing.JSlider();
        visualBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        volumeSlider2 = new javax.swing.JSlider();
        visualBar2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        volumeSlider3 = new javax.swing.JSlider();
        visualBar3 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        volumeSlider4 = new javax.swing.JSlider();
        visualBar4 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        volumeSlider5 = new javax.swing.JSlider();
        visualBar5 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        volumeSlider6 = new javax.swing.JSlider();
        visualBar6 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        volumeSlider7 = new javax.swing.JSlider();
        visualBar7 = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        volumeSlider8 = new javax.swing.JSlider();
        visualBar8 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        volumeSlider9 = new javax.swing.JSlider();
        visualBar9 = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        volumeSlider10 = new javax.swing.JSlider();
        visualBar10 = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        volumeSlider11 = new javax.swing.JSlider();
        visualBar11 = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        volumeSlider12 = new javax.swing.JSlider();
        visualBar12 = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        volumeSlider13 = new javax.swing.JSlider();
        visualBar13 = new javax.swing.JProgressBar();
        jLabel14 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        volumeSlider14 = new javax.swing.JSlider();
        visualBar14 = new javax.swing.JProgressBar();
        jLabel15 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        volumeSlider15 = new javax.swing.JSlider();
        visualBar15 = new javax.swing.JProgressBar();
        jLabel16 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        volumeSlider16 = new javax.swing.JSlider();
        visualBar16 = new javax.swing.JProgressBar();
        jLabel17 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        enableAll = new javax.swing.JCheckBoxMenuItem();
        enableTop = new javax.swing.JCheckBoxMenuItem();
        enableBottom = new javax.swing.JCheckBoxMenuItem();

        freqSplitControl.setTitle("Frequency Split Control");
        freqSplitControl.setMinimumSize(new java.awt.Dimension(540, 200));

        ch1a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch1a.setText("27.5");
        ch1a.setMinimumSize(new java.awt.Dimension(40, 25));
        ch1a.setPreferredSize(new java.awt.Dimension(40, 25));

        ch1b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch1b.setText("69");
        ch1b.setMinimumSize(new java.awt.Dimension(40, 25));
        ch1b.setPreferredSize(new java.awt.Dimension(40, 25));
        ch1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch1bActionPerformed(evt);
            }
        });

        ch2a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch2a.setText("69");
        ch2a.setMinimumSize(new java.awt.Dimension(40, 25));
        ch2a.setPreferredSize(new java.awt.Dimension(40, 25));

        ch2b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch2b.setText("145");
        ch2b.setMinimumSize(new java.awt.Dimension(40, 25));
        ch2b.setPreferredSize(new java.awt.Dimension(40, 25));

        ch3a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch3a.setText("145");
        ch3a.setMinimumSize(new java.awt.Dimension(40, 25));
        ch3a.setPreferredSize(new java.awt.Dimension(40, 25));

        ch3b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch3b.setText("220");
        ch3b.setMinimumSize(new java.awt.Dimension(40, 25));
        ch3b.setPreferredSize(new java.awt.Dimension(40, 25));

        ch4a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch4a.setText("220");
        ch4a.setMinimumSize(new java.awt.Dimension(40, 25));
        ch4a.setPreferredSize(new java.awt.Dimension(40, 25));

        ch4b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch4b.setText("311");
        ch4b.setMinimumSize(new java.awt.Dimension(40, 25));
        ch4b.setPreferredSize(new java.awt.Dimension(40, 25));

        ch5a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch5a.setText("311");
        ch5a.setMinimumSize(new java.awt.Dimension(40, 25));
        ch5a.setPreferredSize(new java.awt.Dimension(40, 25));

        ch5b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch5b.setText("466");
        ch5b.setMinimumSize(new java.awt.Dimension(40, 25));
        ch5b.setPreferredSize(new java.awt.Dimension(40, 25));

        ch6a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch6a.setText("467");
        ch6a.setMinimumSize(new java.awt.Dimension(40, 25));
        ch6a.setPreferredSize(new java.awt.Dimension(40, 25));

        ch6b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch6b.setText("660");
        ch6b.setMinimumSize(new java.awt.Dimension(40, 25));
        ch6b.setPreferredSize(new java.awt.Dimension(40, 25));

        ch7a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch7a.setText("660");
        ch7a.setMinimumSize(new java.awt.Dimension(40, 25));
        ch7a.setPreferredSize(new java.awt.Dimension(40, 25));

        ch7b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch7b.setText("1480");
        ch7b.setMinimumSize(new java.awt.Dimension(40, 25));
        ch7b.setPreferredSize(new java.awt.Dimension(40, 25));

        ch8a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch8a.setText("1480");
        ch8a.setMinimumSize(new java.awt.Dimension(40, 25));
        ch8a.setPreferredSize(new java.awt.Dimension(40, 25));
        ch8a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch8aActionPerformed(evt);
            }
        });

        ch8b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch8b.setText("4186");
        ch8b.setMinimumSize(new java.awt.Dimension(40, 25));
        ch8b.setPreferredSize(new java.awt.Dimension(40, 25));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("CH 1");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("CH 2");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("CH 3");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("CH 4");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("CH 5");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("CH 6");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("CH 7");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("CH 8");

        jLabel26.setText("Band Start");

        jLabel27.setText("Band Stop");

        freqSave.setText("Save");
        freqSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freqSaveActionPerformed(evt);
            }
        });

        freqControlTxt.setText(".");

        javax.swing.GroupLayout freqSplitControlLayout = new javax.swing.GroupLayout(freqSplitControl.getContentPane());
        freqSplitControl.getContentPane().setLayout(freqSplitControlLayout);
        freqSplitControlLayout.setHorizontalGroup(
            freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(freqSplitControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(freqSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(freqSplitControlLayout.createSequentialGroup()
                        .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ch1b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ch1a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(freqSplitControlLayout.createSequentialGroup()
                                .addComponent(ch2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ch3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ch4b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ch5b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ch6b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ch7b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ch8b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(freqSplitControlLayout.createSequentialGroup()
                                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ch2a, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ch3a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ch4a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ch5a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ch6a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ch7a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ch8a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(freqControlTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        freqSplitControlLayout.setVerticalGroup(
            freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, freqSplitControlLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch4a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch5a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch6a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch7a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch8a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(freqSplitControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch4b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch5b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch6b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch7b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch8b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(1, 1, 1)
                .addComponent(freqControlTxt)
                .addGap(3, 3, 3)
                .addComponent(freqSave)
                .addGap(10, 10, 10))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 464));

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));

        play.setText("START");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        outText.setText("Press START to begin");

        inputGroup.add(useMIDIFile);
        useMIDIFile.setText("Input: MIDI File");
        useMIDIFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useMIDIFileActionPerformed(evt);
            }
        });

        inputGroup.add(useMIDIDevice);
        useMIDIDevice.setText("Input: MIDI Device");

        outToDevice.setSelected(true);
        outToDevice.setText("Output to Device (Chair)");
        outToDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outToDeviceActionPerformed(evt);
            }
        });

        inputGroup.add(useWaveFile);
        useWaveFile.setText("Input: Wave File (Frequency Split)");

        inputGroup.add(useWaveFile2);
        useWaveFile2.setSelected(true);
        useWaveFile2.setText("Input: Wave File (Channel Split)");

        delayTuner.setMajorTickSpacing(1);
        delayTuner.setMaximum(8);
        delayTuner.setMinimum(-2);
        delayTuner.setMinorTickSpacing(1);
        delayTuner.setPaintTicks(true);
        delayTuner.setToolTipText("tet");
        delayTuner.setValue(3);

        delayTunerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delayTunerLabel.setText("Latency Tuner");

        javax.swing.GroupLayout latencyPanelLayout = new javax.swing.GroupLayout(latencyPanel);
        latencyPanel.setLayout(latencyPanelLayout);
        latencyPanelLayout.setHorizontalGroup(
            latencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(latencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delayTunerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(latencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(latencyPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(delayTuner, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        latencyPanelLayout.setVerticalGroup(
            latencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(latencyPanelLayout.createSequentialGroup()
                .addComponent(delayTunerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(latencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(latencyPanelLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(delayTuner, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(outText, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(latencyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(useMIDIFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(useMIDIDevice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(outToDevice))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useWaveFile)
                            .addComponent(useWaveFile2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(200, 200, 200))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(outText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(play)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(useMIDIDevice)
                        .addComponent(outToDevice)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useMIDIFile)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(latencyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(useWaveFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(useWaveFile2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider.setMajorTickSpacing(50);
        volumeSlider.setMaximum(200);
        volumeSlider.setMinorTickSpacing(5);
        volumeSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider.setPaintTicks(true);
        volumeSlider.setValue(100);
        volumeSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar_volume.setOrientation(1);

        jLabel1.setText("Volume");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(visualBar_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visualBar_volume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(82, 235));

        volumeSlider1.setMajorTickSpacing(50);
        volumeSlider1.setMaximum(200);
        volumeSlider1.setMinorTickSpacing(5);
        volumeSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider1.setPaintTicks(true);
        volumeSlider1.setValue(100);
        volumeSlider1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar1.setOrientation(1);

        jLabel2.setText("Channel 1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(visualBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volumeSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider2.setMajorTickSpacing(50);
        volumeSlider2.setMaximum(200);
        volumeSlider2.setMinorTickSpacing(5);
        volumeSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider2.setPaintTicks(true);
        volumeSlider2.setValue(100);
        volumeSlider2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar2.setOrientation(1);

        jLabel3.setText("Channel 2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(visualBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(visualBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider3.setMajorTickSpacing(50);
        volumeSlider3.setMaximum(200);
        volumeSlider3.setMinorTickSpacing(5);
        volumeSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider3.setPaintTicks(true);
        volumeSlider3.setValue(100);
        volumeSlider3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar3.setOrientation(1);

        jLabel4.setText("Channel 3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(visualBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider4.setMajorTickSpacing(50);
        volumeSlider4.setMaximum(200);
        volumeSlider4.setMinorTickSpacing(5);
        volumeSlider4.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider4.setPaintTicks(true);
        volumeSlider4.setValue(100);
        volumeSlider4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar4.setOrientation(1);

        jLabel5.setText("Channel 4");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(visualBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visualBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeSlider4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
        );

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider5.setMajorTickSpacing(50);
        volumeSlider5.setMaximum(200);
        volumeSlider5.setMinorTickSpacing(5);
        volumeSlider5.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider5.setPaintTicks(true);
        volumeSlider5.setValue(100);
        volumeSlider5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar5.setOrientation(1);

        jLabel6.setText("Channel 5");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(visualBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volumeSlider5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
        );

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider6.setMajorTickSpacing(50);
        volumeSlider6.setMaximum(200);
        volumeSlider6.setMinorTickSpacing(5);
        volumeSlider6.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider6.setPaintTicks(true);
        volumeSlider6.setValue(100);
        volumeSlider6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar6.setOrientation(1);

        jLabel7.setText("Channel 6");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(visualBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(visualBar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeSlider6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
        );

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider7.setMajorTickSpacing(50);
        volumeSlider7.setMaximum(200);
        volumeSlider7.setMinorTickSpacing(5);
        volumeSlider7.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider7.setPaintTicks(true);
        volumeSlider7.setValue(100);
        volumeSlider7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar7.setOrientation(1);

        jLabel8.setText("Channel 7");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(visualBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeSlider7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualBar7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider8.setMajorTickSpacing(50);
        volumeSlider8.setMaximum(200);
        volumeSlider8.setMinorTickSpacing(5);
        volumeSlider8.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider8.setPaintTicks(true);
        volumeSlider8.setValue(100);
        volumeSlider8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar8.setOrientation(1);

        jLabel9.setText("Channel 8");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(visualBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visualBar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeSlider8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9))
        );

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider9.setMajorTickSpacing(50);
        volumeSlider9.setMaximum(200);
        volumeSlider9.setMinorTickSpacing(5);
        volumeSlider9.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider9.setPaintTicks(true);
        volumeSlider9.setValue(100);
        volumeSlider9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar9.setOrientation(1);

        jLabel10.setText("Channel 9");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(visualBar9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volumeSlider9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualBar9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10))
        );

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider10.setMajorTickSpacing(50);
        volumeSlider10.setMaximum(200);
        volumeSlider10.setMinorTickSpacing(5);
        volumeSlider10.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider10.setPaintTicks(true);
        volumeSlider10.setValue(100);
        volumeSlider10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar10.setOrientation(1);

        jLabel11.setText("Channel 10");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(visualBar10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(visualBar10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeSlider10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11))
        );

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider11.setMajorTickSpacing(50);
        volumeSlider11.setMaximum(200);
        volumeSlider11.setMinorTickSpacing(5);
        volumeSlider11.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider11.setPaintTicks(true);
        volumeSlider11.setValue(100);
        volumeSlider11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar11.setOrientation(1);

        jLabel12.setText("Channel 11");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(visualBar11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeSlider11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualBar11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12))
        );

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider12.setMajorTickSpacing(50);
        volumeSlider12.setMaximum(200);
        volumeSlider12.setMinorTickSpacing(5);
        volumeSlider12.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider12.setPaintTicks(true);
        volumeSlider12.setValue(100);
        volumeSlider12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar12.setOrientation(1);

        jLabel13.setText("Channel 12");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(visualBar12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visualBar12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeSlider12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13))
        );

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));
        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider13.setMajorTickSpacing(50);
        volumeSlider13.setMaximum(200);
        volumeSlider13.setMinorTickSpacing(5);
        volumeSlider13.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider13.setPaintTicks(true);
        volumeSlider13.setValue(100);
        volumeSlider13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar13.setOrientation(1);

        jLabel14.setText("Channel 13");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(visualBar13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volumeSlider13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualBar13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14))
        );

        jPanel17.setBackground(new java.awt.Color(153, 153, 153));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider14.setMajorTickSpacing(50);
        volumeSlider14.setMaximum(200);
        volumeSlider14.setMinorTickSpacing(5);
        volumeSlider14.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider14.setPaintTicks(true);
        volumeSlider14.setValue(100);
        volumeSlider14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar14.setOrientation(1);

        jLabel15.setText("Channel 14");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(visualBar14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(visualBar14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeSlider14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15))
        );

        jPanel18.setBackground(new java.awt.Color(153, 153, 153));
        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider15.setMajorTickSpacing(50);
        volumeSlider15.setMaximum(200);
        volumeSlider15.setMinorTickSpacing(5);
        volumeSlider15.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider15.setPaintTicks(true);
        volumeSlider15.setValue(100);
        volumeSlider15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar15.setOrientation(1);

        jLabel16.setText("Channel 15");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(visualBar15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeSlider15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualBar15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16))
        );

        jPanel19.setBackground(new java.awt.Color(153, 153, 153));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        volumeSlider16.setMajorTickSpacing(50);
        volumeSlider16.setMaximum(200);
        volumeSlider16.setMinorTickSpacing(5);
        volumeSlider16.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider16.setPaintTicks(true);
        volumeSlider16.setValue(100);
        volumeSlider16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        visualBar16.setOrientation(1);

        jLabel17.setText("Channel 16");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(visualBar16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volumeSlider16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visualBar16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeSlider16, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        progress.setPreferredSize(new java.awt.Dimension(146, 5));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Frequency Split Control");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        channelEnable.add(enableAll);
        enableAll.setSelected(true);
        enableAll.setText("Enable All Channels");
        jMenu1.add(enableAll);

        channelEnable.add(enableTop);
        enableTop.setText("Enable only Top Channels");
        enableTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableTopActionPerformed(evt);
            }
        });
        jMenu1.add(enableTop);

        channelEnable.add(enableBottom);
        enableBottom.setText("Enable only Bottom Channels");
        enableBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableBottomActionPerformed(evt);
            }
        });
        jMenu1.add(enableBottom);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        
        if(play.getText().equals("START")){
            play.setText("STOP");
            
            if(useMIDIDevice.isSelected()){
                VibroHelper midiHelper2 = new VibroHelper(this);
                midiHelper2.midiKeyboard();
            }           
            if (useMIDIFile.isSelected()){
                VibroHelper midiHelper = new VibroHelper(this);            
                try{           
                    if(!fileFound){
                        int rVal = c.showOpenDialog(VibroGUI.this);
                        if (rVal == JFileChooser.APPROVE_OPTION) {
                            outText.setText(c.getSelectedFile().getName());
                            fileFound=true;
                            midiHelper.translate(c.getSelectedFile(),2);                    
                        }
                    }else{
                        midiHelper.translate(c.getSelectedFile(),2);
                    }            
                }catch(Exception e){System.out.println("AN error occured");} 
            }
            else if (useWaveFile.isSelected()){
                VibroHelper wavHelper = new VibroHelper(this);
                int rVal = c.showOpenDialog(VibroGUI.this);
                if (rVal == JFileChooser.APPROVE_OPTION) {
                    fileFound=true;
                    outText.setText("Loading file...please wait");
                    String [] filePath = {c.getSelectedFile().getAbsolutePath()};                
                    float[][]data = FreqFilter.main(filePath);
                    for(int i=1; i<=8; i++){
                        wavHelper.playWave(i,data); 
                    }
                    latencyPanel.setVisible(true);                    
                    outText.setText(c.getSelectedFile().getName());                    
                }
            }
            else if (useWaveFile2.isSelected()){
                VibroHelper wavHelper = new VibroHelper(this);
                int rVal = c.showOpenDialog(VibroGUI.this);
                if (rVal == JFileChooser.APPROVE_OPTION) {
                    fileFound=true;
                    outText.setText("Loading file...please wait");
                    String [] filePath = {c.getSelectedFile().getAbsolutePath()};                
                    float[][]data = ChanFilter.main(filePath);
                    System.out.println(data.length+" lewr");
                    for(int i=1; i<data.length; i++){
                        wavHelper.playWave(i,data); 
                    }
                    setChannels(data.length-1);
                    latencyPanel.setVisible(true);                    
                    outText.setText(c.getSelectedFile().getName());                    
                }
            }     
        }else{  
            latencyPanel.setVisible(false);
            play.setText("START");
            outText.setText("");
            progress.setValue(0);            
        }
        
         
    }//GEN-LAST:event_playActionPerformed

    
    private void useFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useFileActionPerformed

    private void outToDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outToDeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outToDeviceActionPerformed

    private void useWaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useWaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useWaveActionPerformed

    private void enableBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableBottomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enableBottomActionPerformed

    private void enableTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableTopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enableTopActionPerformed

    private void useMIDIFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useMIDIFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useMIDIFileActionPerformed

    private void ch1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch1bActionPerformed

    private void ch8aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch8aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch8aActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        freqSplitControl.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void freqSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freqSaveActionPerformed
        // TODO add your handling code here:
        double[] data = new double[16];
        try{          
            data[0]=Double.parseDouble(ch1a.getText()); data[1]=Double.parseDouble(ch1b.getText());
            data[2]=Double.parseDouble(ch2a.getText()); data[3]=Double.parseDouble(ch2b.getText());
            data[4]=Double.parseDouble(ch3a.getText()); data[5]=Double.parseDouble(ch3b.getText());
            data[6]=Double.parseDouble(ch4a.getText()); data[7]=Double.parseDouble(ch4b.getText());
            data[8]=Double.parseDouble(ch5a.getText()); data[9]=Double.parseDouble(ch5b.getText());
            data[10]=Double.parseDouble(ch6a.getText()); data[11]=Double.parseDouble(ch6b.getText());
            data[12]=Double.parseDouble(ch7a.getText()); data[13]=Double.parseDouble(ch7b.getText());
            data[14]=Double.parseDouble(ch8a.getText()); data[15]=Double.parseDouble(ch8b.getText());
            boolean error = false;
            for(int i=0; i<8; i++){
                if(data[i*2]>data[i*2+1]) error = true;                
            }
            if(error) freqControlTxt.setText("Start band must be less than stop band");
            else{ 
                FreqFilter.write(data);
                freqControlTxt.setText("");
                freqSplitControl.setVisible(false);
            }
        }catch(NumberFormatException n){
            freqControlTxt.setText("Non-Numeric characters are not allowed");
        }
        
        
    }//GEN-LAST:event_freqSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VibroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VibroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VibroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VibroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VibroGUI().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ch1a;
    private javax.swing.JTextField ch1b;
    private javax.swing.JTextField ch2a;
    private javax.swing.JTextField ch2b;
    private javax.swing.JTextField ch3a;
    private javax.swing.JTextField ch3b;
    private javax.swing.JTextField ch4a;
    private javax.swing.JTextField ch4b;
    private javax.swing.JTextField ch5a;
    private javax.swing.JTextField ch5b;
    private javax.swing.JTextField ch6a;
    private javax.swing.JTextField ch6b;
    private javax.swing.JTextField ch7a;
    private javax.swing.JTextField ch7b;
    private javax.swing.JTextField ch8a;
    private javax.swing.JTextField ch8b;
    private javax.swing.ButtonGroup channelEnable;
    protected javax.swing.JSlider delayTuner;
    private javax.swing.JLabel delayTunerLabel;
    private javax.swing.JCheckBoxMenuItem enableAll;
    protected javax.swing.JCheckBoxMenuItem enableBottom;
    protected javax.swing.JCheckBoxMenuItem enableTop;
    private javax.swing.JLabel freqControlTxt;
    private javax.swing.JButton freqSave;
    private javax.swing.JDialog freqSplitControl;
    private javax.swing.ButtonGroup inputGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel latencyPanel;
    protected javax.swing.JLabel outText;
    protected javax.swing.JRadioButton outToDevice;
    protected javax.swing.JButton play;
    protected javax.swing.JProgressBar progress;
    protected javax.swing.JRadioButton useMIDIDevice;
    protected javax.swing.JRadioButton useMIDIFile;
    protected javax.swing.JRadioButton useWaveFile;
    private javax.swing.JRadioButton useWaveFile2;
    public javax.swing.JProgressBar visualBar1;
    public javax.swing.JProgressBar visualBar10;
    public javax.swing.JProgressBar visualBar11;
    public javax.swing.JProgressBar visualBar12;
    public javax.swing.JProgressBar visualBar13;
    public javax.swing.JProgressBar visualBar14;
    public javax.swing.JProgressBar visualBar15;
    public javax.swing.JProgressBar visualBar16;
    public javax.swing.JProgressBar visualBar2;
    public javax.swing.JProgressBar visualBar3;
    public javax.swing.JProgressBar visualBar4;
    public javax.swing.JProgressBar visualBar5;
    public javax.swing.JProgressBar visualBar6;
    public javax.swing.JProgressBar visualBar7;
    public javax.swing.JProgressBar visualBar8;
    public javax.swing.JProgressBar visualBar9;
    public javax.swing.JProgressBar visualBar_volume;
    public javax.swing.JSlider volumeSlider;
    public javax.swing.JSlider volumeSlider1;
    public javax.swing.JSlider volumeSlider10;
    public javax.swing.JSlider volumeSlider11;
    public javax.swing.JSlider volumeSlider12;
    public javax.swing.JSlider volumeSlider13;
    public javax.swing.JSlider volumeSlider14;
    public javax.swing.JSlider volumeSlider15;
    public javax.swing.JSlider volumeSlider16;
    public javax.swing.JSlider volumeSlider2;
    public javax.swing.JSlider volumeSlider3;
    public javax.swing.JSlider volumeSlider4;
    public javax.swing.JSlider volumeSlider5;
    public javax.swing.JSlider volumeSlider6;
    public javax.swing.JSlider volumeSlider7;
    public javax.swing.JSlider volumeSlider8;
    public javax.swing.JSlider volumeSlider9;
    // End of variables declaration//GEN-END:variables
}
